apiVersion: v1
entries:
  consul:
  - annotations:
      artifacthub.io/images: |
        - name: consul
          image: hashicorp/consul:1.20.0
        - name: consul-k8s-control-plane
          image: hashicorp/consul-k8s-control-plane:1.6.0
        - name: consul-dataplane
          image: hashicorp/consul-dataplane:1.6.0
        - name: envoy
          image: envoyproxy/envoy:v1.25.11
      artifacthub.io/license: MPL-2.0
      artifacthub.io/links: |
        - name: Documentation
          url: https://www.consul.io/docs/k8s
        - name: hashicorp/consul
          url: https://github.com/hashicorp/consul
        - name: hashicorp/consul-k8s
          url: https://github.com/hashicorp/consul-k8s
      artifacthub.io/prerelease: "false"
      artifacthub.io/signKey: |
        fingerprint: C874011F0AB405110D02105534365D9472D7468F
        url: https://keybase.io/hashicorp/pgp_keys.asc
    apiVersion: v2
    appVersion: 1.20.0
    created: "2024-10-22T11:47:13.246980761Z"
    description: Official HashiCorp Consul Chart
    digest: 6710a7fd7f898de4c0d8bba9816e555a559d61a7437bc8f53d99576d326393a7
    home: https://www.consul.io
    icon: https://raw.githubusercontent.com/hashicorp/consul-k8s/main/assets/icon.png
    kubeVersion: '>=1.22.0-0'
    name: consul
    sources:
    - https://github.com/hashicorp/consul
    - https://github.com/hashicorp/consul-k8s
    urls:
    - charts/consul-1.6.0.tgz
    version: 1.6.0
  database:
  - apiVersion: v2
    appVersion: "13.16"
    created: "2024-10-22T08:10:26.488695393Z"
    description: A Helm chart for DB_CONNECTION Database Postgresql 13.16
    digest: fe97cabdcdee723ea54239ee63a1cfa055c24a44ae46e9b9498643b4af2757af
    name: database
    type: application
    urls:
    - charts/database-1.tgz
    version: "1"
  spring:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2024-10-22T08:10:26.499695299Z"
    description: A Helm chart for DB_CONNECT Backend 1.0
    digest: 27b8ae90c488df6f7efb25a401129ea00534aee11aa286dd438f826677b922eb
    name: spring
    type: application
    urls:
    - charts/spring-1.tgz
    version: "1"
generated: "2024-10-25T14:53:01Z"
serverInfo: {}
