apiVersion: v1
data:
  application.properties: |
    spring.application.name=DB_CONNECT
    # spring.datasource.url=jdbc:mysql://localhost:3306/db
    spring.datasource.url=jdbc:postgresql://database-database-service:5432/java_db
    spring.datasource.username=karam
    spring.datasource.password=root
    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.generate-ddl=true
    spring.jpa.hibernate.ddl-auto=update
kind: ConfigMap
metadata:
  name: spring-properties
