apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: "/mnt/data"
