---
- name: Install and configure dhcp on RHEL
  hosts: localhost
  become: yes
  tasks:
    - name: Install DHCP
      ansible.builtin.package:
        name: dhcp-server
        state: present
    - name: Configure DHCP
      copy:
        src: ../files/dhcpd.conf
        dest: /etc/dhcp/dhcpd.conf
    - name: Start DHCP service
      service:
        name: dhcpd
        state: started
        enabled: true
