apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
data:
  postgres-uri: {{ with .Values.secret.postgres_uri }}
    {{- list "jdbc:postgres://" .username ":" .password "@" $.Release.Name "-" .dbChartName "-service:" .port "/" .dbConnection | join "" | b64enc | quote }}
    {{- end }}

    #fullnameOverride: myCustomFullName
