apiVersion: v1
data:
  application.properties: |
    spring.ldap.embedded.ldif=classpath:test-server.ldif
    spring.ldap.embedded.base-dn=dc=springframework,dc=org
    spring.ldap.embedded.port=8389  
    spring.application.name=DB_CONNECT
    # spring.datasource.url=jdbc:mysql://localhost:3306/db
    spring.datasource.url=jdbc:postgresql://database-database-service:5432/java_db
    spring.datasource.username=karam
    spring.datasource.password=root
    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.generate-ddl=true
    spring.jpa.hibernate.ddl-auto=update
    spring.cloud.consul.host=consul-server.consul.svc
    spring.cloud.consul.port=8500
    spring.cloud.consul.enabled=true
    spring.cloud.consul.discovery.healthCheckPath=/actuator/health
    spring.cloud.consul.discovery.healthCheckInterval=5s
    spring.cloud.consul.discovery.instance-id=${spring.application.name}
    spring.cloud.consul.discovery.scheme=http
    spring.cloud.consul.discovery.hostname=${spring.application.name}
    spring.cloud.consul.discovery.port=${server.port}

kind: ConfigMap
metadata:
  name: spring-properties
