image:
  repository: privateRegistry/my-tools/db_connect
  tag: "1.0"

service:
  containerPort: 8080
  targetPort: 8080
  port: 8080

replicaCount: 1
database:
  uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQGRlbW8tZ3Vlc3Rib29rLWRhdGFiYXNlLXNlcnZpY2U6MjcwMTcvZ3Vlc3Rib29rP2F1dGhTb3VyY2U9YWRtaW4K
  
secret:
  postgres_uri:
    username: <DB_USERNAME>
    password: <DB_PASSWORD>
    dbChartName: database
    port: 5432
    dbConnection: db-connect

ingress:
  host: spring.minikube.local
  enabled: true
