apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
    spec:
      containers:
        - image: postgres:13.16
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
                key: postgres-username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
                key: postgres-password
          name: postgres
          ports:
            - name: postgres
              containerPort: {{ .Values.service.containerPort }}
          volumeMounts:
            - name: {{ .Release.Name }}-{{ .Chart.Name }}-volume
              mountPath: /var/postgresql/data/pgdata
      volumes:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ .Chart.Name }}-pvc
